name: Run API Tests and Publish Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests-and-publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run Pytest
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: pytest --alluredir=allure-results
        continue-on-error: true

      - name: Generate Allure Report
        uses: andgineer/allure-report@v3.6
        with:
          allure-results: allure-results
          gh-pages: gh-pages 

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.USER_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages