name: Run API tests with Allure reporting

on: 
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs: 
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Allure Commandline
      run: |
        sudo apt-get update
        sudo apt-get install -y allure

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest
      env:
        API_KEY: ${{ secrets.API_KEY }}
        BASE_URL: ${{ secrets.BASE_URL }}
      run: pytest --alluredir=allure-results

    - name: Generate Allure report
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Upload Allure report as artifact
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-report

    
